import { Router } from "express";
import orderSchema from '../validators/order.validator.js';
import { integrityCheck,integrityId } from "../middlewares/validate.middleware.js";
import { getAllOrders, getOrderById, getUserOrders, createOrder, updateOrderStatus } from "../controllers/order.controller.js";
const routerOrders = Router();
routerOrders.param(["id", "userId"],integrityId);
routerOrders.get("/", getAllOrders);
routerOrders.get("/:id", getOrderById);
routerOrders.get("/user/:userId", getUserOrders);
routerOrders.post("/", integrityCheck(orderSchema), createOrder);
routerOrders.patch("/:id/status", updateOrderStatus);
export default routerOrders;
