import { Router } from "express";
import { getAllProducts,getSpecificProduct,addProduct,deleteProduct,updateProduct,updateQuantity } from "../controllers/products.controller.js";
import { integrityCheck,integrityId } from "../middlewares/validate.middleware.js";
import productSchema from "../validators/product.validator.js";
import uploadMiddleware from "../middlewares/upload.middleware.js";
const routerProducts=Router();
routerProducts.param("id",integrityId);
routerProducts.get("/",getAllProducts);
routerProducts.get("/:id",getSpecificProduct);
routerProducts.post("/",uploadMiddleware('imageUrl'),integrityCheck(productSchema),addProduct);
routerProducts.delete("/:id",deleteProduct);
routerProducts.put("/:id",uploadMiddleware('imageUrl'),integrityCheck(productSchema),updateProduct);
routerProducts.patch("/:id",updateQuantity);
export default routerProducts;